spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ultraplatform
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100        # 컬렉션 조회 최적화를 위한 설정


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace